version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
      
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - npm run devStart
            
workflows:
  build-deploy:
    jobs:
     
      - build
      
