GET http://localhost:3000/company

###

GET http://localhost:3000/login/62ffc214082d6a97ca0f1071


###

 POST http://localhost:3000/employee
Content-Type: application/json

 {
	    "companyId": "63568a2b07755ec6eb490b2a",
        "firstName": "Bafokeng",
        "lastName": "Futhoane",
        "gender": "Male",
        "email": "bafokeng.futhoane@bothouniversity.com",
        "bankAccNo": "184739493003",
        "bankName": "Nedbank",
        "employmentStart": "2012-12-04"
        
		}

###

PATCH  http://localhost:3000/localhost:3000/company/63121a940561217a1e9d5836
Content-Type: application/json

 {
   "CompanyName": "BRO Inc" 
  
 }

###

 DELETE http://localhost:3000/localhost:3000/company/63121a940561217a1e9d5836